import Foundation

/// A pending transaction recorded on Apple Watch and queued for the iPhone
/// to commit into SwiftData.
///
/// `id` is generated by the Watch and carried through verbatim so the iPhone
/// side can deduplicate retries.
public struct TransactionDraft: Equatable, Hashable, Codable, Sendable {
    public let id: UUID
    public let categoryId: UUID
    public let accountId: UUID
    public let amount: Decimal
    public let date: Date

    public init(
        id: UUID = UUID(),
        categoryId: UUID,
        accountId: UUID,
        amount: Decimal,
        date: Date = Date()
    ) {
        self.id = id
        self.categoryId = categoryId
        self.accountId = accountId
        self.amount = amount
        self.date = date
    }

    public var isValid: Bool {
        amount > 0
    }
}
