import Foundation

/// A pending transaction recorded on Apple Watch and queued for the iPhone
/// to commit into SwiftData.
///
/// `id` is generated by the Watch and carried through verbatim so the iPhone
/// side can deduplicate retries.
public struct TransactionDraft: Equatable, Hashable, Codable, Sendable {
    /// Unique identifier generated on Apple Watch and preserved end-to-end.
    /// Used by the iPhone side to deduplicate retries of the same draft.
    public let id: UUID

    /// The category this expense should be filed under.
    public let categoryId: UUID

    /// The account this expense should be debited from.
    public let accountId: UUID

    /// The monetary value. Watch UI enforces integer-only entry; storage is
    /// `Decimal` to stay aligned with `Transaction.amount`.
    public let amount: Decimal

    /// When the expense occurred. Defaults to "now" at draft creation time.
    public let date: Date

    public init(
        id: UUID = UUID(),
        categoryId: UUID,
        accountId: UUID,
        amount: Decimal,
        date: Date = Date()
    ) {
        self.id = id
        self.categoryId = categoryId
        self.accountId = accountId
        self.amount = amount
        self.date = date
    }

    public var isValid: Bool {
        amount > 0
    }
}
